backend:
  name: git-gateway
  # name: test-repo
  # repo: hendhyhutomo/gatsbyv2

media_folder: static/assets
public_folder: assets
collections:
  - label: 'Settings'
    name: 'settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'src/settings/general.md'
        label: 'General Setting'
        name: 'general'
        delete: false
        description: 'General Site Settings'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'general_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'General Setting', required: true, }
          - { label: 'Web Name', name: 'web_name', widget: 'string', default: 'HERBAMOJO', required: true, }
          - { label: 'Disable Journal', name: 'journaldisable', widget: "boolean", default: false, required: true, }
          - label: "META INFO"
            name: "seo"
            widget: "object"
            required: false
            fields:
            - { label: 'Short Description', name: 'seo_shortdesc', widget: 'string', hint: 'Max (200 Characters).', default: '', required: false,}
            - { label: 'Keywords', name: 'seo_keywords', widget: 'string',  hint: 'Each Keywords are seperated with a comma (","). Max (200 Characters).', default: '',required: false,}
            - { name: 'seo_image', label: 'Image', widget: 'image', pattern: [\.(jpe?g|png)$], hint: 'width: 1200px, height: 600px', default: '', required: false,}
          - label: "Footer"
            name: "footer"
            widget: "object"
            required: false
            fields:
            - { label: 'Email', name: 'email', widget: 'string', hint: 'Input Herbamojo Contact Email', default: '', required: false,}
            - { label: 'Instagram', name: 'ig_link', widget: 'string',  hint: 'Input link starting with https://', default: '',required: false,}
            - { name: 'wa_no', label: 'Whatsapp No.', widget: 'string', hint: 'Input the Registered Whatsapp Number. Only Number, no space or plus (+) sign.', default: '', required: false,}
          - label: "Navigation"
            name: "navigation"
            widget: "object"
            required: false
            fields:
            - label: "Home"
              name: "home"
              widget: "object"
              required: false
              fields:
              - { label: 'English', name: 'en', widget: 'string', default: 'Home', required: false}
              - { label: 'Indonesia', name: 'id', widget: 'string', default: 'Home',required: false}
            - label: "Journal"
              name: "journal"
              widget: "object"
              required: false
              fields:
              - { label: 'English', name: 'en', widget: 'string', default: 'Journal', required: false}
              - { label: 'Indonesia', name: 'id', widget: 'string', default: 'Journal',required: false}
      - file: 'src/settings/home.md'
        label: 'Home Setting'
        name: 'home'
        delete: false
        description: 'Landing Page Settings'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'home_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Home Setting', required: true, }
      - file: 'src/settings/slug.md'
        label: 'URL Redirect'
        name: 'slug'
        delete: false
        description: 'Creates URL Redirector'
        fields:
          - { name: 'issetting', label: 'issetting', widget: 'hidden', default: true, required: true, }
          - { name: 'contenttype', label: 'contenttype', widget: 'hidden', default: 'slug_setting', required: true, }
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'URL Redirect', required: true, }
          - name: 'redirect'
            label: 'URL LIST'
            widget: 'list'
            label_singular: 'Redirect'
            required: false
            fields:
              - { label: 'From (Internal Slug)', name: 'from', widget: 'string',
                  hint: 'Lower Characters (a-z), Numericals (0-9), dash (-), forwardslash (/) and must not start with a /, Minimum 3 Characters, eg: "redirect-to-google"',
                  pattern: [
                    [
                      '^([a-z0-9]+(?:(-|/)[a-z0-9]+)*){3,}$',
                      'Invalid Characters'
                    ],]
                  }
              - { label: 'To', name: 'to', widget: 'string',
                  hint: 'Lower Characters (a-z), Numericals (0-9), dash (-), forwardslash (/) and must not start with a /, Minimum 3 Characters, eg: External URL "https://google.com", Internal: "google"',
                  pattern: [
                  [
                    '^([a-z0-9]+(?:(-|/)[a-z0-9]+)*){3,}$',
                      'Invalid Characters'
                  ],] }
              - { label: 'Active', name: 'status', widget: 'boolean', default: false }
